#!/usr/bin/env bash
set -euo pipefail

workspace_root="${FLEET_OODA_CODEX_WORKSPACE_ROOT:-/docker/fleet}"
cd "$workspace_root"

state_root="${FLEET_OODA_CODEX_STATE_ROOT:-${workspace_root}/state/fleet_ooda_codex_timer}"
run_root="${state_root}/runs"
mkdir -p "$run_root"

lock_path="${state_root}/run.lock"
exec 9>"$lock_path"
if ! flock -n 9; then
  printf '%s skipped: previous fleet OODA Codex run is still active\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"${state_root}/timer.log"
  exit 0
fi

timestamp="$(date -u +'%Y%m%dT%H%M%SZ')"
current_run="${run_root}/${timestamp}"
mkdir -p "$current_run"
ln -sfn "runs/${timestamp}" "${state_root}/latest"

codex_bin="${FLEET_OODA_CODEX_BIN:-}"
if [[ -z "$codex_bin" ]]; then
  if [[ -x /home/tibor/bin/codex ]]; then
    codex_bin=/home/tibor/bin/codex
  else
    codex_bin="$(command -v codex || true)"
  fi
fi
if [[ -z "$codex_bin" || ! -x "$codex_bin" ]]; then
  echo "codex binary not found" | tee "${current_run}/error.txt" >&2
  exit 127
fi

target_shards="${FLEET_OODA_CODEX_TARGET_SHARDS:-13}"
minimum_productive_shards="${FLEET_OODA_CODEX_MIN_PRODUCTIVE_SHARDS:-8}"
timeout_seconds="${FLEET_OODA_CODEX_TIMEOUT_SECONDS:-1200}"
post_guard_timeout_seconds="${FLEET_OODA_CODEX_POST_GUARD_TIMEOUT_SECONDS:-120}"
model_arg=()
if [[ -n "${FLEET_OODA_CODEX_MODEL:-}" ]]; then
  model_arg=(-m "${FLEET_OODA_CODEX_MODEL}")
fi
timer_dry_run=0
if [[ "${1:-}" == "--dry-run" ]]; then
  timer_dry_run=1
fi

guard_path="${current_run}/timer_guard.json"
guard_stderr_path="${current_run}/timer_guard.stderr.log"
guard_args=(--once --target-active "$target_shards" --minimum-active "$minimum_productive_shards")
if [[ "$timer_dry_run" == "1" ]]; then
  guard_args+=(--dry-run)
fi
timeout 300s python3 scripts/fleet_ooda_timer_guard.py \
  "${guard_args[@]}" \
  >"$guard_path" \
  2>"$guard_stderr_path" || true

{
  printf 'generated_at=%s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  printf 'workspace_root=%s\n' "$workspace_root"
  printf 'target_shards=%s\n' "$target_shards"
  printf 'minimum_productive_shards=%s\n' "$minimum_productive_shards"
  printf '\n[timer-guard]\n'
  cat "$guard_path" 2>/dev/null || true
  printf '\n[timer-guard-stderr]\n'
  cat "$guard_stderr_path" 2>/dev/null || true
  printf '\n[healthcheck]\n'
  timeout 20s python3 scripts/healthcheck_design_supervisor.py --json || true
  printf '\n[status]\n'
  timeout 35s python3 scripts/chummer_design_supervisor.py status --json || true
  printf '\n[docker-ps]\n'
  docker compose -f docker-compose.yml ps fleet-controller fleet-design-supervisor fleet-design-overwatch || true
  printf '\n[disk]\n'
  df -h / || true
  printf '\n[memory]\n'
  free -h || true
} >"${current_run}/preflight.txt" 2>&1

prompt_path="${current_run}/prompt.md"
cat >"$prompt_path" <<PROMPT
You are Codex running an unattended 30-minute Fleet OODA maintenance slice.

Mission:
- OODA the fleet and improve it.
- Make sure enough Chummer design supervisor shards are running.
- Remove blockers instead of only reporting them.
- Keep the human reader first: leave concise evidence, clear final status, and no noisy churn.

Operating constraints:
- Work from /docker/fleet.
- Do not ask for confirmation.
- Do not revert unrelated user or worker changes.
- Keep Fleet workers on EA/codexea; this scheduled operator Codex pass may use the host Codex session.
- Use existing local scripts and contracts before inventing new mechanisms.
- Wrap status, live-refresh, guard, keeper, docker-log, and test commands in explicit timeouts. Do not let one diagnostic command consume the whole timer slice.
- Do not delete source repos, git packs, user data, or large artifacts unless they are clearly generated by the current fleet run and safe to remove.
- Do not modify this timer/guard unless the timer or guard is the blocker.
- Finish within roughly ${timeout_seconds}s.
- Known external credential blocker: Mac release promotion can stop with "set CHUMMER_RELEASE_UPLOAD_TICKET or CHUMMER_RELEASE_UPLOAD_TOKEN for HTTP release promotion". Do not fabricate that secret. Classify it as an operator credential blocker, give the exact export/file-based rerun command, and move on to blockers you can actually fix.

Non-negotiable timer guard:
- First read ${guard_path}.
- If timer_guard.status is blocked, fix those blockers before trusting Fleet status.
- If timer_guard.requires_codex_patch is true, patch the broken source across /docker/EA and/or /docker/fleet, rebuild/recreate the affected service, and rerun scripts/fleet_ooda_timer_guard.py --once --target-active ${target_shards} --minimum-active ${minimum_productive_shards}.
- Provider-health invariants are hard gates: a provider or lane must not be marked ready with configured_slots > 0 and ready_slots <= 0; low-credit core/core_rescue must not be treated as routable; survival must be backed by a ready BrowserAct/ChatPlayground provider.
- Do not accept "8 active shards" as healthy if the guard says provider-health is cached, stale, lying, or survival is not live-routable.
- If the guard repaired runtime env, provider-health cache, or service state, verify the change landed with a fresh guard pass.

Definition of enough shards:
- Target configured shard count: ${target_shards}.
- Respect live provider and memory caps, but do not accept an artificial 3/13 maintenance throttle unless there is current critical host pressure.
- If provider capacity allows it, keep at least ${minimum_productive_shards} active/streaming Chummer design supervisor shards.
- If active shards are below the provider-allowed cap, repair the cause: runtime profile, stale supervisor, locks, parked shards, provider health cache, or worker stall loops.

Required OODA loop:
1. Observe:
   - Run scripts/fleet_ooda_timer_guard.py --once --target-active ${target_shards} --minimum-active ${minimum_productive_shards}; treat failures as blockers to fix, not as report-only diagnostics.
   - Run healthcheck_design_supervisor.py --json.
   - Run timeout 60s scripts/chummer_design_supervisor.py status --json and use timeout 90s scripts/chummer_design_supervisor.py status --json --live-refresh if completion proof fields are stale or missing.
   - Check docker compose ps for fleet-controller, fleet-design-supervisor, and fleet-design-overwatch.
   - Check recent supervisor logs, disk, and memory.
   - Run scripts/fleet_ooda_keeper.py --once --target-active 13 when the controller queue needs more work scheduled.
2. Orient:
   - Identify current blockers: low active shards, stale status, repeated worker_silent_stalled, provider capacity, disk pressure, failing proof gates, review holds, or dead services.
3. Decide and Act:
   - Apply targeted fixes.
   - Restart only the affected service when needed.
   - If standard dispatch was lowered without critical pressure, restore standard or an appropriate wider profile.
   - Keep the longer watchdog/stall guards if they are preventing false 240s kills.
   - Clear safe generated junk if disk pressure is blocking work.
4. Verify:
   - Re-run healthcheck.
   - Re-run status and confirm active shards are at the live provider/memory cap or a justified limit.
   - Confirm blocker count and proof gates.
   - Leave a concise final answer with changed files, commands run, and remaining risks.

Preflight snapshot for this run is in:
${current_run}/preflight.txt

Timer guard JSON for this run is in:
${guard_path}
PROMPT

if [[ "$timer_dry_run" == "1" ]]; then
  printf 'codex_bin=%s\nprompt_path=%s\nrun_dir=%s\n' "$codex_bin" "$prompt_path" "$current_run"
  exit 0
fi

export HOME="${HOME:-/home/tibor}"
export PATH="/home/tibor/bin:/home/tibor/.local/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

printf '%s started fleet OODA Codex run %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$current_run" >>"${state_root}/timer.log"

set +e
timeout --foreground "${timeout_seconds}s" "$codex_bin" exec \
  --dangerously-bypass-approvals-and-sandbox \
  --skip-git-repo-check \
  --color never \
  -C "$workspace_root" \
  --add-dir /docker \
  -o "${current_run}/last_message.txt" \
  "${model_arg[@]}" \
  - <"$prompt_path" \
  >"${current_run}/stdout.log" \
  2>"${current_run}/stderr.log"
rc=$?
set -e

post_guard_path="${current_run}/post_codex_timer_guard.json"
post_guard_stderr_path="${current_run}/post_codex_timer_guard.stderr.log"
timeout "${post_guard_timeout_seconds}s" python3 scripts/fleet_ooda_timer_guard.py \
  --once \
  --target-active "$target_shards" \
  --minimum-active "$minimum_productive_shards" \
  >"$post_guard_path" \
  2>"$post_guard_stderr_path" || true

printf '%s finished fleet OODA Codex run %s rc=%s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$current_run" "$rc" >>"${state_root}/timer.log"
exit "$rc"
