#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ARCHIVE="$SCRIPT_DIR/macos-proof-bundle.tgz"
export BUNDLE_ARCHIVE
TARGET_ROOT=/docker/chummercomplete/chummer6-ui/Docker/Downloads
export TARGET_ROOT
if [ ! -s "$BUNDLE_ARCHIVE" ]; then
  echo "Missing host proof bundle: $BUNDLE_ARCHIVE"
  exit 1
fi
python3 -c 'import os, pathlib, tarfile; bundle=pathlib.Path(os.environ['"'"'BUNDLE_ARCHIVE'"'"']); members=tarfile.open(bundle, '"'"'r:gz'"'"').getmembers(); bad=[member.name for member in members if member.name.startswith('"'"'/'"'"') or '"'"'..'"'"' in pathlib.PurePosixPath(member.name).parts]; assert not any('"'"'..'"'"' in parts for parts in [pathlib.PurePosixPath(member.name).parts for member in members]), '"'"'external-proof-bundle-path-unsafe:'"'"' + '"'"','"'"'.join(sorted(set(bad)))'
mkdir -p "$TARGET_ROOT"
tar -xzf "$BUNDLE_ARCHIVE" -C "$TARGET_ROOT"
python3 -c 'import os, json, pathlib; manifest_path=pathlib.Path(os.environ['"'"'TARGET_ROOT'"'"']) / '"'"'external-proof-manifest.json'"'"'; expected=json.loads('"'"'{"host": "macos", "request_count": 2, "requests": [{"expected_installer_bundle_relative_path": "files/chummer-avalonia-osx-arm64-installer.dmg", "expected_installer_sha256": "", "expected_startup_smoke_receipt_path": "startup-smoke/startup-smoke-avalonia-osx-arm64.receipt.json", "tuple_id": "avalonia:osx-arm64:macos"}, {"expected_installer_bundle_relative_path": "files/chummer-blazor-desktop-osx-arm64-installer.dmg", "expected_installer_sha256": "", "expected_startup_smoke_receipt_path": "startup-smoke/startup-smoke-blazor-desktop-osx-arm64.receipt.json", "tuple_id": "blazor-desktop:osx-arm64:macos"}], "schema_version": 1}'"'"'); assert manifest_path.is_file(), '"'"'external-proof-bundle-manifest-missing:'"'"' + str(manifest_path); payload=json.loads(manifest_path.read_text(encoding='"'"'utf-8'"'"')); assert payload == expected, '"'"'external-proof-bundle-manifest-mismatch:'"'"' + str(manifest_path) + '"'"':expected='"'"' + json.dumps(expected, sort_keys=True) + '"'"':actual='"'"' + json.dumps(payload, sort_keys=True)'
test -s "$TARGET_ROOT/files/chummer-avalonia-osx-arm64-installer.dmg"
test -s "$TARGET_ROOT/startup-smoke/startup-smoke-avalonia-osx-arm64.receipt.json"
test -s "$TARGET_ROOT/files/chummer-blazor-desktop-osx-arm64-installer.dmg"
test -s "$TARGET_ROOT/startup-smoke/startup-smoke-blazor-desktop-osx-arm64.receipt.json"
python3 -c 'import json, os, pathlib; target_root=pathlib.Path(os.environ['"'"'TARGET_ROOT'"'"']); tuple_id='"'"'avalonia:osx-arm64:macos'"'"'; relative='"'"'startup-smoke/startup-smoke-avalonia-osx-arm64.receipt.json'"'"'; contract=json.loads('"'"'{"head_id": "avalonia", "host_class_contains": "macos", "platform": "macos", "ready_checkpoint": "pre_ui_event_loop", "rid": "osx-arm64", "status_any_of": ["pass", "passed", "ready"]}'"'"'); path=target_root / relative; assert path.is_file(), f'"'"'external-proof-bundle-receipt-missing:{tuple_id}:{path}'"'"'; payload=json.loads(path.read_text(encoding='"'"'utf-8'"'"')); payload=payload if isinstance(payload, dict) else {}; status=str(payload.get('"'"'status'"'"') or '"'"''"'"').strip().lower(); expected_statuses=[str(token).strip().lower() for token in (contract.get('"'"'status_any_of'"'"') or []) if str(token).strip()]; head_id=str(payload.get('"'"'headId'"'"') or '"'"''"'"').strip().lower(); platform=str(payload.get('"'"'platform'"'"') or '"'"''"'"').strip().lower(); rid=str(payload.get('"'"'rid'"'"') or '"'"''"'"').strip().lower(); ready_checkpoint=str(payload.get('"'"'readyCheckpoint'"'"') or '"'"''"'"').strip().lower(); host_class=str(payload.get('"'"'hostClass'"'"') or '"'"''"'"').strip().lower(); expected_head=str(contract.get('"'"'head_id'"'"') or '"'"''"'"').strip().lower(); expected_platform=str(contract.get('"'"'platform'"'"') or '"'"''"'"').strip().lower(); expected_rid=str(contract.get('"'"'rid'"'"') or '"'"''"'"').strip().lower(); expected_ready=str(contract.get('"'"'ready_checkpoint'"'"') or '"'"''"'"').strip().lower(); expected_host_contains=str(contract.get('"'"'host_class_contains'"'"') or '"'"''"'"').strip().lower(); assert ((not expected_statuses or status in expected_statuses) and (not expected_head or head_id == expected_head) and (not expected_platform or platform == expected_platform) and (not expected_rid or rid == expected_rid) and (not expected_ready or ready_checkpoint == expected_ready) and (not expected_host_contains or expected_host_contains in host_class), f'"'"'receipt-contract-mismatch:{tuple_id}:{path}:status={status}:head={head_id}:platform={platform}:rid={rid}:ready={ready_checkpoint}:host_class={host_class}:contract={contract}'"'"')'
python3 -c 'import json, os, pathlib; target_root=pathlib.Path(os.environ['"'"'TARGET_ROOT'"'"']); tuple_id='"'"'blazor-desktop:osx-arm64:macos'"'"'; relative='"'"'startup-smoke/startup-smoke-blazor-desktop-osx-arm64.receipt.json'"'"'; contract=json.loads('"'"'{"head_id": "blazor-desktop", "host_class_contains": "macos", "platform": "macos", "ready_checkpoint": "pre_ui_event_loop", "rid": "osx-arm64", "status_any_of": ["pass", "passed", "ready"]}'"'"'); path=target_root / relative; assert path.is_file(), f'"'"'external-proof-bundle-receipt-missing:{tuple_id}:{path}'"'"'; payload=json.loads(path.read_text(encoding='"'"'utf-8'"'"')); payload=payload if isinstance(payload, dict) else {}; status=str(payload.get('"'"'status'"'"') or '"'"''"'"').strip().lower(); expected_statuses=[str(token).strip().lower() for token in (contract.get('"'"'status_any_of'"'"') or []) if str(token).strip()]; head_id=str(payload.get('"'"'headId'"'"') or '"'"''"'"').strip().lower(); platform=str(payload.get('"'"'platform'"'"') or '"'"''"'"').strip().lower(); rid=str(payload.get('"'"'rid'"'"') or '"'"''"'"').strip().lower(); ready_checkpoint=str(payload.get('"'"'readyCheckpoint'"'"') or '"'"''"'"').strip().lower(); host_class=str(payload.get('"'"'hostClass'"'"') or '"'"''"'"').strip().lower(); expected_head=str(contract.get('"'"'head_id'"'"') or '"'"''"'"').strip().lower(); expected_platform=str(contract.get('"'"'platform'"'"') or '"'"''"'"').strip().lower(); expected_rid=str(contract.get('"'"'rid'"'"') or '"'"''"'"').strip().lower(); expected_ready=str(contract.get('"'"'ready_checkpoint'"'"') or '"'"''"'"').strip().lower(); expected_host_contains=str(contract.get('"'"'host_class_contains'"'"') or '"'"''"'"').strip().lower(); assert ((not expected_statuses or status in expected_statuses) and (not expected_head or head_id == expected_head) and (not expected_platform or platform == expected_platform) and (not expected_rid or rid == expected_rid) and (not expected_ready or ready_checkpoint == expected_ready) and (not expected_host_contains or expected_host_contains in host_class), f'"'"'receipt-contract-mismatch:{tuple_id}:{path}:status={status}:head={head_id}:platform={platform}:rid={rid}:ready={ready_checkpoint}:host_class={host_class}:contract={contract}'"'"')'
echo "Host proof bundle ingest complete: $BUNDLE_ARCHIVE"
